#!/usr/bin/env python3
"""
Smart Doc Generator - 自动从源代码生成 API 文档
功能：分析 Python/JS/TS 代码，生成 Markdown 格式的 API 文档
作者: 196408245@qq.com
"""

import os
import re
import ast
import argparse
from pathlib import Path
from typing import List, Dict, Optional
from dataclasses import dataclass


@dataclass
class FunctionInfo:
    """函数信息"""
    name: str
    docstring: str
    args: List[str]
    returns: Optional[str]
    decorators: List[str]


class CodeAnalyzer:
    """代码分析器基类"""
    
    def extract_functions(self, filepath: str) -> List[FunctionInfo]:
        raise NotImplementedError


class PythonAnalyzer(CodeAnalyzer):
    """Python 代码分析器"""
    
    def extract_functions(self, filepath: str) -> List[FunctionInfo]:
        """从 Python 文件提取函数信息"""
        functions = []
        try:
            with open(filepath, 'r', encoding='utf-8') as f:
                tree = ast.parse(f.read())
            
            for node in ast.walk(tree):
                if isinstance(node, ast.FunctionDef):
                    func_info = FunctionInfo(
                        name=node.name,
                        docstring=ast.get_docstring(node) or '',
                        args=[arg.arg for arg in node.args.args],
                        returns=self._get_return_annotation(node),
                        decorators=[dec.id if isinstance(dec, ast.Name) else str(dec) 
                                   for dec in node.decorator_list]
                    )
                    functions.append(func_info)
        except Exception as e:
            print(f"Error parsing {filepath}: {e}")
        return functions
    
    def _get_return_annotation(self, node: ast.FunctionDef) -> Optional[str]:
        """获取返回类型注解"""
        if node.returns:
            return ast.unparse(node.returns)
        return None


class JavaScriptAnalyzer(CodeAnalyzer):
    """JavaScript/TypeScript 代码分析器"""
    
    def extract_functions(self, filepath: str) -> List[FunctionInfo]:
        """从 JS/TS 文件提取函数信息"""
        functions = []
        try:
            with open(filepath, 'r', encoding='utf-8') as f:
                content = f.read()
            
            # 匹配函数声明: function name(args) { ... }
            pattern1 = r'function\s+(\w+)\s*\(([^)]*)\)\s*\{([^}]*?)(?:\n\s*})'
            matches1 = re.findall(pattern1, content, re.MULTILINE | re.DOTALL)
            
            for match in matches1:
                name, args, body = match
                docstring = self._extract_js_docstring(body)
                functions.append(FunctionInfo(
                    name=name,
                    docstring=docstring,
                    args=[a.strip() for a in args.split(',') if a.strip()],
                    returns=None,
                    decorators=[]
                ))
            
            # 匹配箭头函数: const name = (args) => ...
            pattern2 = r'const\s+(\w+)\s*=\s*\(([^)]*)\)\s*=>'
            matches2 = re.findall(pattern2, content)
            
            for match in matches2:
                name, args = match
                if not any(f.name == name for f in functions):
                    functions.append(FunctionInfo(
                        name=name,
                        docstring='',
                        args=[a.strip() for a in args.split(',') if a.strip()],
                        returns=None,
                        decorators=[]
                    ))
                    
        except Exception as e:
            print(f"Error parsing {filepath}: {e}")
        return functions
    
    def _extract_js_docstring(self, body: str) -> str:
        """提取 JS 文档注释"""
        match = re.search(r'/\*\*\s*\n(.*?)\n\s*\*/', body, re.DOTALL)
        if match:
            lines = match.group(1).split('\n')
            return '\n'.join(line.strip().lstrip('*') for line in lines)
        return ''


class DocumentationGenerator:
    """文档生成器"""
    
    def __init__(self, project_name: str, author: str, description: str = ""):
        self.project_name = project_name
        self.author = author
        self.description = description
    
    def generate_markdown(self, functions: List[FunctionInfo], 
                         source_file: str) -> str:
        """生成 Markdown 格式文档"""
        lines = [
            f"# {self.project_name} API Documentation",
            "",
            f"**Source File:** `{source_file}`",
            "",
            f"**Generated by:** Smart Doc Generator",
            "",
            "---",
            "",
            "## Table of Contents",
        ]
        
        # 生成目录
        for i, func in enumerate(functions, 1):
            lines.append(f"{i}. [{func.name}](#{func.name.replace('_', '-')})")
        lines.append("")
        
        # 生成函数文档
        lines.append("---")
        lines.append("")
        lines.append("## Functions")
        lines.append("")
        
        for func in functions:
            lines.append(f"### `{func.name}`")
            lines.append("")
            
            if func.decorators:
                lines.append("**Decorators:** " + 
                           ", ".join(f"`@{d}`" for d in func.decorators))
                lines.append("")
            
            # 参数
            if func.args:
                lines.append("**Parameters:**")
                lines.append("")
                for arg in func.args:
                    lines.append(f"- `{arg}`")
                lines.append("")
            
            # 返回值
            if func.returns:
                lines.append(f"**Returns:** `{func.returns}`")
                lines.append("")
            
            # 文档字符串
            if func.docstring:
                lines.append("**Description:**")
                lines.append("")
                lines.append(func.docstring)
                lines.append("")
        
        return '\n'.join(lines)


class SmartDocGenerator:
    """智能文档生成器主类"""
    
    SUPPORTED_EXTENSIONS = {
        '.py': PythonAnalyzer,
        '.js': JavaScriptAnalyzer,
        '.ts': JavaScriptAnalyzer,
        '.jsx': JavaScriptAnalyzer,
        '.tsx': JavaScriptAnalyzer,
    }
    
    def __init__(self, author: str = ""):
        self.author = author
    
    def analyze_file(self, filepath: str) -> List[FunctionInfo]:
        """分析单个文件"""
        ext = Path(filepath).suffix.lower()
        analyzer_class = self.SUPPORTED_EXTENSIONS.get(ext)
        
        if not analyzer_class:
            print(f"Unsupported file type: {ext}")
            return []
        
        analyzer = analyzer_class()
        return analyzer.extract_functions(filepath)
    
    def generate_docs(self, source_path: str, output_path: str = None,
                     project_name: str = None) -> str:
        """生成文档"""
        source_path = Path(source_path)
        
        if not source_path.exists():
            raise FileNotFoundError(f"Source path not found: {source_path}")
        
        # 确定项目名
        if not project_name:
            project_name = source_path.stem if source_path.is_file() else source_path.name
        
        # 收集所有函数
        all_functions = []
        
        if source_path.is_file():
            all_functions = self.analyze_file(str(source_path))
        else:
            for ext, _ in self.SUPPORTED_EXTENSIONS.items():
                for filepath in source_path.rglob(f'*{ext}'):
                    funcs = self.analyze_file(str(filepath))
                    for f in funcs:
                        all_functions.append(f)
        
        # 生成文档
        generator = DocumentationGenerator(
            project_name=project_name,
            author=self.author,
            description=f"Auto-generated documentation for {project_name}"
        )
        
        doc = generator.generate_markdown(all_functions, str(source_path))
        
        # 保存文档
        if output_path:
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(doc)
            print(f"Documentation saved to: {output_path}")
        
        return doc


def main():
    """主函数"""
    parser = argparse.ArgumentParser(
        description='Smart Doc Generator - 自动从源代码生成 API 文档',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python main.py --source ./src --output docs/api.md --name "MyProject"
  python main.py --source main.py --output README.md
  python main.py --source ./src --recursive
        """
    )
    
    parser.add_argument('--source', '-s', required=True,
                       help='Source file or directory to analyze')
    parser.add_argument('--output', '-o',
                       help='Output file path for generated documentation')
    parser.add_argument('--name', '-n',
                       help='Project name for documentation')
    parser.add_argument('--recursive', '-r', action='store_true',
                       help='Recursively scan directories')
    
    args = parser.parse_args()
    
    # 创建生成器
    generator = SmartDocGenerator(author="196408245@qq.com")
    
    try:
        # 生成文档
        doc = generator.generate_docs(
            source_path=args.source,
            output_path=args.output,
            project_name=args.name
        )
        
        if not args.output:
            print(doc)
        else:
            print("Documentation generated successfully!")
            
    except Exception as e:
        print(f"Error: {e}")
        return 1
    
    return 0


if __name__ == '__main__':
    exit(main())
